function addsandbox()
    thisPath = fileparts( mfilename( 'fullpath' ) );
    addpath( fullfile(...
        thisPath,...
        'code',...
        'fxgraphics' ) );
    addpath( fullfile(...
        thisPath,...
        'test' ) );
    addpath( fullfile(...
        thisPath,...
        'demo' ) );
end